export const transactions = [
  {
    id: 1,
    date: '2025-08-01',
    type: 'INCOME',
    amount: 5000,
    description: 'Salary',
    isRecurring: true,
  },
  {
    id: 2,
    date: '2025-08-02',
    type: 'EXPENSE',
    amount: 1200,
    description: 'Rent',
    isRecurring: true,
  },
  {
    id: 3,
    date: '2025-08-03',
    type: 'INCOME',
    amount: 3000,
    description: 'Freelance',
    isRecurring: false,
  },
  {
    id: 4,
    date: '2025-08-04',
    type: 'EXPENSE',
    amount: 500,
    description: 'Groceries',
    isRecurring: false,
  },
  {
    id: 5,
    date: '2025-08-05',
    type: 'EXPENSE',
    amount: 700,
    description: 'Utilities',
    isRecurring: true,
  },
  {
    id: 6,
    date: '2025-08-06',
    type: 'INCOME',
    amount: 2000,
    description: 'Investment',
    isRecurring: false,
  },
  {
    id: 7,
    date: '2025-08-07',
    type: 'EXPENSE',
    amount: 300,
    description: 'Shopping',
    isRecurring: false,
  },
  {
    id: 8,
    date: '2025-08-08',
    type: 'INCOME',
    amount: 1500,
    description: 'Bonus',
    isRecurring: false,
  },
  {
    id: 9,
    date: '2025-08-08',
    type: 'EXPENSE',
    amount: 700,
    description: 'Insurance',
    isRecurring: true,
  },
  {
    id: 10,
    date: '2025-08-09',
    type: 'EXPENSE',
    amount: 800,
    description: 'Insurance',
    isRecurring: true,
  },
  {
    id: 11,
    date: '2025-08-10',
    type: 'INCOME',
    amount: 4000,
    description: 'Consulting',
    isRecurring: false,
  },
  {
    id: 12,
    date: '2025-08-11',
    type: 'EXPENSE',
    amount: 250,
    description: 'Gas',
    isRecurring: false,
  },
  {
    id: 13,
    date: '2025-08-12',
    type: 'EXPENSE',
    amount: 1000,
    description: 'Travel',
    isRecurring: false,
  },
  {
    id: 14,
    date: '2025-08-13',
    type: 'INCOME',
    amount: 2500,
    description: 'Sales Commission',
    isRecurring: false,
  },
  {
    id: 15,
    date: '2025-08-14',
    type: 'EXPENSE',
    amount: 600,
    description: 'Healthcare',
    isRecurring: true,
  },
  {
    id: 16,
    date: '2025-08-15',
    type: 'INCOME',
    amount: 3500,
    description: 'Project Payment',
    isRecurring: false,
  },
  {
    id: 17,
    date: '2025-08-16',
    type: 'EXPENSE',
    amount: 450,
    description: 'Dining Out',
    isRecurring: false,
  },
  {
    id: 18,
    date: '2025-08-17',
    type: 'INCOME',
    amount: 2700,
    description: 'Stock Dividends',
    isRecurring: true,
  },
  {
    id: 19,
    date: '2025-08-18',
    type: 'EXPENSE',
    amount: 320,
    description: 'Phone Bill',
    isRecurring: true,
  },

  // July 2025 data
  {
    id: 20,
    date: '2025-07-30',
    type: 'INCOME',
    amount: 5000,
    description: 'Salary',
    isRecurring: true,
  },
  {
    id: 21,
    date: '2025-07-29',
    type: 'EXPENSE',
    amount: 1200,
    description: 'Rent',
    isRecurring: true,
  },
  {
    id: 22,
    date: '2025-07-28',
    type: 'EXPENSE',
    amount: 400,
    description: 'Groceries',
    isRecurring: false,
  },
  {
    id: 23,
    date: '2025-07-27',
    type: 'INCOME',
    amount: 1800,
    description: 'Side Project',
    isRecurring: false,
  },
  {
    id: 24,
    date: '2025-07-26',
    type: 'EXPENSE',
    amount: 200,
    description: 'Entertainment',
    isRecurring: false,
  },
  {
    id: 25,
    date: '2025-07-25',
    type: 'EXPENSE',
    amount: 150,
    description: 'Coffee & Meals',
    isRecurring: false,
  },
  {
    id: 26,
    date: '2025-07-24',
    type: 'INCOME',
    amount: 900,
    description: 'Refund',
    isRecurring: false,
  },
  {
    id: 27,
    date: '2025-07-23',
    type: 'EXPENSE',
    amount: 350,
    description: 'Car Maintenance',
    isRecurring: false,
  },
  {
    id: 28,
    date: '2025-07-22',
    type: 'EXPENSE',
    amount: 250,
    description: 'Gym Membership',
    isRecurring: true,
  },
  {
    id: 29,
    date: '2025-07-21',
    type: 'INCOME',
    amount: 2200,
    description: 'Freelance Design',
    isRecurring: false,
  },
  {
    id: 30,
    date: '2025-07-20',
    type: 'EXPENSE',
    amount: 180,
    description: 'Subscriptions',
    isRecurring: true,
  },
  {
    id: 31,
    date: '2025-07-19',
    type: 'EXPENSE',
    amount: 420,
    description: 'Medical Bills',
    isRecurring: false,
  },
  {
    id: 32,
    date: '2025-07-18',
    type: 'INCOME',
    amount: 1600,
    description: 'Bonus',
    isRecurring: false,
  },
  {
    id: 33,
    date: '2025-07-17',
    type: 'EXPENSE',
    amount: 300,
    description: 'Shopping',
    isRecurring: false,
  },
  {
    id: 34,
    date: '2025-07-16',
    type: 'EXPENSE',
    amount: 95,
    description: 'Internet Bill',
    isRecurring: true,
  },
  {
    id: 35,
    date: '2025-07-15',
    type: 'INCOME',
    amount: 3200,
    description: 'Client Payment',
    isRecurring: false,
  },

  // June 2025 data
  {
    id: 36,
    date: '2025-06-30',
    type: 'INCOME',
    amount: 5000,
    description: 'Salary',
    isRecurring: true,
  },
  {
    id: 37,
    date: '2025-06-29',
    type: 'EXPENSE',
    amount: 1200,
    description: 'Rent',
    isRecurring: true,
  },
  {
    id: 38,
    date: '2025-06-28',
    type: 'EXPENSE',
    amount: 380,
    description: 'Groceries',
    isRecurring: false,
  },
  {
    id: 39,
    date: '2025-06-27',
    type: 'INCOME',
    amount: 2100,
    description: 'Investment Returns',
    isRecurring: false,
  },
  {
    id: 40,
    date: '2025-06-26',
    type: 'EXPENSE',
    amount: 600,
    description: 'Vacation',
    isRecurring: false,
  },
  {
    id: 41,
    date: '2025-06-25',
    type: 'EXPENSE',
    amount: 280,
    description: 'Dining Out',
    isRecurring: false,
  },
  {
    id: 42,
    date: '2025-06-24',
    type: 'INCOME',
    amount: 1400,
    description: 'Part-time Job',
    isRecurring: false,
  },
  {
    id: 43,
    date: '2025-06-23',
    type: 'EXPENSE',
    amount: 150,
    description: 'Gas',
    isRecurring: false,
  },
  {
    id: 44,
    date: '2025-06-22',
    type: 'EXPENSE',
    amount: 220,
    description: 'Clothing',
    isRecurring: false,
  },
  {
    id: 45,
    date: '2025-06-21',
    type: 'INCOME',
    amount: 800,
    description: 'Cashback',
    isRecurring: false,
  },
  {
    id: 46,
    date: '2025-06-20',
    type: 'EXPENSE',
    amount: 320,
    description: 'Home Supplies',
    isRecurring: false,
  },
  {
    id: 47,
    date: '2025-06-19',
    type: 'EXPENSE',
    amount: 450,
    description: 'Electronics',
    isRecurring: false,
  },
  {
    id: 48,
    date: '2025-06-18',
    type: 'INCOME',
    amount: 2800,
    description: 'Freelance Web Dev',
    isRecurring: false,
  },
  {
    id: 49,
    date: '2025-06-17',
    type: 'EXPENSE',
    amount: 120,
    description: 'Books',
    isRecurring: false,
  },
  {
    id: 50,
    date: '2025-06-16',
    type: 'EXPENSE',
    amount: 350,
    description: 'Utilities',
    isRecurring: true,
  },
  {
    id: 51,
    date: '2025-06-15',
    type: 'INCOME',
    amount: 1900,
    description: 'Consulting Fee',
    isRecurring: false,
  },

  // May 2025 data
  {
    id: 52,
    date: '2025-05-31',
    type: 'INCOME',
    amount: 5000,
    description: 'Salary',
    isRecurring: true,
  },
  {
    id: 53,
    date: '2025-05-30',
    type: 'EXPENSE',
    amount: 1200,
    description: 'Rent',
    isRecurring: true,
  },
  {
    id: 54,
    date: '2025-05-29',
    type: 'EXPENSE',
    amount: 460,
    description: 'Groceries',
    isRecurring: false,
  },
  {
    id: 55,
    date: '2025-05-28',
    type: 'INCOME',
    amount: 1200,
    description: 'Tutoring',
    isRecurring: false,
  },
  {
    id: 56,
    date: '2025-05-27',
    type: 'EXPENSE',
    amount: 180,
    description: 'Entertainment',
    isRecurring: false,
  },
  {
    id: 57,
    date: '2025-05-26',
    type: 'EXPENSE',
    amount: 240,
    description: 'Restaurant',
    isRecurring: false,
  },
  {
    id: 58,
    date: '2025-05-25',
    type: 'INCOME',
    amount: 3400,
    description: 'Project Completion',
    isRecurring: false,
  },
  {
    id: 59,
    date: '2025-05-24',
    type: 'EXPENSE',
    amount: 300,
    description: 'Car Insurance',
    isRecurring: true,
  },
  {
    id: 60,
    date: '2025-05-23',
    type: 'EXPENSE',
    amount: 150,
    description: 'Phone Bill',
    isRecurring: true,
  },
  {
    id: 61,
    date: '2025-05-22',
    type: 'INCOME',
    amount: 950,
    description: 'Gift Money',
    isRecurring: false,
  },
  {
    id: 62,
    date: '2025-05-21',
    type: 'EXPENSE',
    amount: 270,
    description: 'Pharmacy',
    isRecurring: false,
  },
  {
    id: 63,
    date: '2025-05-20',
    type: 'EXPENSE',
    amount: 400,
    description: 'Home Repair',
    isRecurring: false,
  },
  {
    id: 64,
    date: '2025-05-19',
    type: 'INCOME',
    amount: 2600,
    description: 'Freelance Marketing',
    isRecurring: false,
  },
  {
    id: 65,
    date: '2025-05-18',
    type: 'EXPENSE',
    amount: 190,
    description: 'Streaming Services',
    isRecurring: true,
  },
  {
    id: 66,
    date: '2025-05-17',
    type: 'EXPENSE',
    amount: 340,
    description: 'Travel',
    isRecurring: false,
  },
  {
    id: 67,
    date: '2025-05-16',
    type: 'INCOME',
    amount: 1800,
    description: 'Stock Sale',
    isRecurring: false,
  },
  {
    id: 68,
    date: '2025-05-15',
    type: 'EXPENSE',
    amount: 280,
    description: 'Fitness',
    isRecurring: true,
  },

  // April 2025 data
  {
    id: 69,
    date: '2025-04-30',
    type: 'INCOME',
    amount: 5000,
    description: 'Salary',
    isRecurring: true,
  },
  {
    id: 70,
    date: '2025-04-29',
    type: 'EXPENSE',
    amount: 1200,
    description: 'Rent',
    isRecurring: true,
  },
  {
    id: 71,
    date: '2025-04-28',
    type: 'EXPENSE',
    amount: 520,
    description: 'Groceries',
    isRecurring: false,
  },
  {
    id: 72,
    date: '2025-04-27',
    type: 'INCOME',
    amount: 1500,
    description: 'Side Business',
    isRecurring: false,
  },
  {
    id: 73,
    date: '2025-04-26',
    type: 'EXPENSE',
    amount: 200,
    description: 'Entertainment',
    isRecurring: false,
  },
  {
    id: 74,
    date: '2025-04-25',
    type: 'EXPENSE',
    amount: 160,
    description: 'Coffee Shops',
    isRecurring: false,
  },
  {
    id: 75,
    date: '2025-04-24',
    type: 'INCOME',
    amount: 2900,
    description: 'Contract Work',
    isRecurring: false,
  },
  {
    id: 76,
    date: '2025-04-23',
    type: 'EXPENSE',
    amount: 380,
    description: 'Car Payment',
    isRecurring: true,
  },
  {
    id: 77,
    date: '2025-04-22',
    type: 'EXPENSE',
    amount: 220,
    description: 'Clothing',
    isRecurring: false,
  },
  {
    id: 78,
    date: '2025-04-21',
    type: 'INCOME',
    amount: 1100,
    description: 'Tax Refund',
    isRecurring: false,
  },
  {
    id: 79,
    date: '2025-04-20',
    type: 'EXPENSE',
    amount: 290,
    description: 'Home Decor',
    isRecurring: false,
  },
  {
    id: 80,
    date: '2025-04-19',
    type: 'EXPENSE',
    amount: 180,
    description: 'Personal Care',
    isRecurring: false,
  },
  {
    id: 81,
    date: '2025-04-18',
    type: 'INCOME',
    amount: 2400,
    description: 'Photography Gig',
    isRecurring: false,
  },

  // March 2025 data
  {
    id: 82,
    date: '2025-03-31',
    type: 'INCOME',
    amount: 5000,
    description: 'Salary',
    isRecurring: true,
  },
  {
    id: 83,
    date: '2025-03-30',
    type: 'EXPENSE',
    amount: 1200,
    description: 'Rent',
    isRecurring: true,
  },
  {
    id: 84,
    date: '2025-03-29',
    type: 'EXPENSE',
    amount: 440,
    description: 'Groceries',
    isRecurring: false,
  },
  {
    id: 85,
    date: '2025-03-28',
    type: 'INCOME',
    amount: 1800,
    description: 'Bonus',
    isRecurring: false,
  },
  {
    id: 86,
    date: '2025-03-27',
    type: 'EXPENSE',
    amount: 320,
    description: 'Dining Out',
    isRecurring: false,
  },
  {
    id: 87,
    date: '2025-03-26',
    type: 'EXPENSE',
    amount: 150,
    description: 'Gas',
    isRecurring: false,
  },

  // February 2025 data
  {
    id: 88,
    date: '2025-02-28',
    type: 'INCOME',
    amount: 5000,
    description: 'Salary',
    isRecurring: true,
  },
  {
    id: 89,
    date: '2025-02-27',
    type: 'EXPENSE',
    amount: 1200,
    description: 'Rent',
    isRecurring: true,
  },
  {
    id: 90,
    date: '2025-02-26',
    type: 'EXPENSE',
    amount: 380,
    description: 'Groceries',
    isRecurring: false,
  },
  {
    id: 91,
    date: '2025-02-25',
    type: 'INCOME',
    amount: 2500,
    description: 'Freelance',
    isRecurring: false,
  },
  {
    id: 92,
    date: '2025-02-24',
    type: 'EXPENSE',
    amount: 450,
    description: 'Car Repair',
    isRecurring: false,
  },
  {
    id: 93,
    date: '2025-02-23',
    type: 'EXPENSE',
    amount: 200,
    description: 'Shopping',
    isRecurring: false,
  },
  {
    id: 94,
    date: '2025-02-22',
    type: 'INCOME',
    amount: 1800,
    description: 'Investment',
    isRecurring: false,
  },
  {
    id: 95,
    date: '2025-02-21',
    type: 'EXPENSE',
    amount: 300,
    description: 'Utilities',
    isRecurring: true,
  },
  {
    id: 96,
    date: '2025-02-20',
    type: 'EXPENSE',
    amount: 120,
    description: 'Internet',
    isRecurring: true,
  },
  {
    id: 97,
    date: '2025-02-19',
    type: 'INCOME',
    amount: 950,
    description: 'Bonus',
    isRecurring: false,
  },
  {
    id: 98,
    date: '2025-02-18',
    type: 'EXPENSE',
    amount: 280,
    description: 'Dining',
    isRecurring: false,
  },
  {
    id: 99,
    date: '2025-02-17',
    type: 'EXPENSE',
    amount: 350,
    description: 'Healthcare',
    isRecurring: true,
  },
  {
    id: 100,
    date: '2025-02-16',
    type: 'INCOME',
    amount: 2200,
    description: 'Consulting',
    isRecurring: false,
  },
];

export const DATE_RANGES = {
  '7D': { label: 'Last 7 Days', days: 7 },
  '1M': { label: 'Last Month', days: 30 },
  '3M': { label: 'Last 3 Months', days: 90 },
  '6M': { label: 'Last 6 Months', days: 180 },
  ALL: { label: 'All Time', days: null },
};
