# Generated by Django 5.2.3 on 2025-08-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockdata',
            name='open_price',
        ),
        migrations.AddField(
            model_name='stockdata',
            name='open',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='volume',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='prev_close',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
