# Generated by Django 5.2.3 on 2025-08-17 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_remove_stockdata_open_price_stockdata_open_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockdata',
            old_name='open',
            new_name='open_price',
        ),
    ]
