# Generated by Django 5.2.3 on 2025-08-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_rename_open_stockdata_open_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='symbol',
            field=models.CharField(max_length=50),
        ),
    ]
