# Generated by Django 5.2.3 on 2025-08-19 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='logo_url',
        ),
    ]
