# Generated by Django 5.2.3 on 2025-08-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_stock_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='exchange',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sector',
            field=models.CharField(choices=[('TECH', 'Technology'), ('FIN', 'Financials'), ('HC', 'Healthcare'), ('IND', 'Industrials'), ('CONS', 'Consumer'), ('EN', 'Energy'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=50),
        ),
    ]
