# Generated by Django 5.2.3 on 2025-07-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustom',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
