# Generated by Django 5.2.3 on 2025-08-08 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_usercustom_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
