class ErrorCodes:
    EMAIL_GENERATION_FAILURE = "ERR_EMAIL_GEN"
    EMAIL_NOT_RECEIVED = "ERR_EMAIL_NOT_RECEIVED"
    OTP_GENERATION_FAILURE = "ERR_OTP_GEN"
    OTP_NOT_RECEIVED = "ERR_OTP_NOT_RECEIVED"
    OTP_EXPIRED = "ERR_OTP_EXPIRED"
    OTP_INVALID = "ERR_OTP_INVALID"
    USER_NOT_FOUND = "ERR_NO_USER"
    INTERNAL_ERROR = "ERR_INTERNAL_SERVER"
    VALIDATION_ERROR = "ERR_VALIDATION"
    TOKEN_ERROR = "ERR_TOKEN"
    