# Generated by Django 5.2.3 on 2025-08-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('SALARY', 'Salary'), ('BUSINESS', 'Business Income'), ('INVESTMENT', 'Investment Returns'), ('FOOD', 'Food & Dining'), ('TRANSPORT', 'Transportation'), ('SHOPPING', 'Shopping'), ('ENTERTAINMENT', 'Entertainment'), ('BILLS', 'Bills & Utilities'), ('HEALTHCARE', 'Healthcare'), ('EDUCATION', 'Education'), ('TRAVEL', 'Travel'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=20),
        ),
    ]
