# Generated by Django 5.2.3 on 2025-08-19 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_alter_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('SALARY', 'Salary'), ('BUSINESS', 'Business Income'), ('INVESTMENT', 'Investment Returns'), ('FREELANCE', 'Freelance/Consulting'), ('RENTAL', 'Rental Income'), ('BONUS', 'Bonus/Commission'), ('REFUND', 'Refunds'), ('GIFT', 'Gifts Received'), ('FOOD', 'Food & Dining'), ('GROCERIES', 'Groceries'), ('TRANSPORT', 'Transportation'), ('FUEL', 'Fuel/Gas'), ('BILLS', 'Bills & Utilities'), ('RENT', 'Rent/Mortgage'), ('INSURANCE', 'Insurance'), ('HEALTHCARE', 'Healthcare'), ('SHOPPING', 'Shopping'), ('CLOTHING', 'Clothing & Accessories'), ('ENTERTAINMENT', 'Entertainment'), ('EDUCATION', 'Education'), ('TRAVEL', 'Travel'), ('FITNESS', 'Fitness & Sports'), ('PERSONAL_CARE', 'Personal Care'), ('SUBSCRIPTIONS', 'Subscriptions'), ('SAVINGS', 'Savings'), ('INVESTMENTS', 'Investments'), ('LOAN_PAYMENT', 'Loan Payments'), ('CREDIT_CARD', 'Credit Card Payment'), ('BANK_FEES', 'Bank Fees'), ('TAXES', 'Taxes'), ('CHILDCARE', 'Childcare'), ('PET_CARE', 'Pet Care'), ('CHARITY', 'Charity/Donations'), ('GIFTS_GIVEN', 'Gifts Given'), ('HOME_IMPROVEMENT', 'Home Improvement'), ('MAINTENANCE', 'Maintenance & Repairs'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=20),
        ),
    ]
